'use client'

import { useState } from 'react'
import Link from 'next/link'
import { ArrowLeft, Check, ChevronDown, Eye, ImagePlus, Paperclip, Plus, Save, Sparkles, Table2 } from 'lucide-react'
import { QUESTION_TYPES, type QuestionType } from '@/features/question-bank/types'

export default function QuestionEditor({ questionId }: { questionId?: string }) {
  const [type, setType] = useState<QuestionType>('multiple_choice')
  const [title, setTitle] = useState('')
  const [body, setBody] = useState('')
  const [preview, setPreview] = useState(false)
  const choiceBased = ['multiple_choice', 'multiple_select', 'true_false'].includes(type)

  return <div className="space-y-5"><header className="flex flex-col gap-4 rounded-3xl border border-gray-200/80 bg-white p-5 shadow-sm dark:border-white/10 dark:bg-gray-900 sm:flex-row sm:items-center"><Link href="/dashboard/question-bank" className="grid h-9 w-9 place-items-center rounded-xl border border-gray-200 dark:border-white/10"><ArrowLeft className="h-4 w-4" /></Link><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><h1 className="truncate text-lg font-semibold">{questionId ? 'Edit question' : 'Create question'}</h1><span className="rounded-lg bg-amber-50 px-2 py-1 text-[10px] font-bold text-amber-700 dark:bg-amber-500/10 dark:text-amber-200">DRAFT</span></div><p className="mt-1 flex items-center gap-1 text-xs text-gray-400"><Check className="h-3 w-3" /> Local draft ready · persistence connects after migration</p></div><button onClick={() => setPreview(!preview)} className="inline-flex h-9 items-center gap-2 rounded-xl border border-gray-200 px-3 text-sm font-semibold dark:border-white/10"><Eye className="h-4 w-4" /> Preview</button><button className="inline-flex h-9 items-center gap-2 rounded-xl bg-gray-950 px-4 text-sm font-semibold text-white dark:bg-white dark:text-gray-950"><Save className="h-4 w-4" /> Save draft</button></header>

  {preview ? <QuestionPreview title={title} body={body} type={type} /> : <div className="grid gap-5 xl:grid-cols-[1fr_320px]"><main className="space-y-5"><EditorCard title="Question"><Field label="Internal title" hint="Used in search and management"><input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="e.g. Photosynthesis energy conversion" className="editor-input" /></Field><Field label="Question body" hint="Rich text, equations, images, and tables"><div className="overflow-hidden rounded-2xl border border-gray-200 dark:border-white/10"><div className="flex gap-1 border-b border-gray-100 p-2 dark:border-white/10"><Tool icon={ImagePlus} label="Image" /><Tool icon={Table2} label="Table" /><Tool icon={Sparkles} label="Equation" /><Tool icon={Paperclip} label="Attach" /></div><textarea value={body} onChange={(event) => setBody(event.target.value)} rows={7} placeholder="Write the question here…" className="w-full resize-y bg-transparent p-4 text-sm outline-none" /></div></Field></EditorCard>
    {choiceBased && <EditorCard title="Options & correct answer"><p className="text-xs text-gray-400">Select {type === 'multiple_select' ? 'all correct answers' : 'the correct answer'}.</p><div className="mt-4 space-y-3">{(type === 'true_false' ? ['True','False'] : ['Option A','Option B','Option C','Option D']).map((option, index) => <label key={option} className="flex items-center gap-3 rounded-2xl border border-gray-200 p-3 dark:border-white/10"><input type={type === 'multiple_select' ? 'checkbox' : 'radio'} name="answer" /><input defaultValue={option} className="min-w-0 flex-1 bg-transparent text-sm outline-none" disabled={type === 'true_false'} />{type !== 'true_false' && index > 1 && <button className="text-xs text-gray-400">Remove</button>}</label>)}</div>{type !== 'true_false' && <button className="mt-3 inline-flex items-center gap-1 text-xs font-semibold text-blue-600"><Plus className="h-3.5 w-3.5" /> Add option</button>}</EditorCard>}
    {!choiceBased && <EditorCard title="Correct answer"><Field label={type === 'long_answer' ? 'Evaluation rubric' : 'Expected answer'}><textarea rows={4} placeholder={type === 'numerical' ? 'Answer and acceptable tolerance' : 'Enter the answer or grading guidance…'} className="editor-input h-auto py-3" /></Field></EditorCard>}
    <EditorCard title="Teaching support"><Field label="Explanation"><textarea rows={4} placeholder="Explain why the answer is correct…" className="editor-input h-auto py-3" /></Field><Field label="Hints"><textarea rows={2} placeholder="Add optional hints for students…" className="editor-input h-auto py-3" /></Field></EditorCard>
    <EditorCard title="Attachments"><div className="rounded-2xl border border-dashed border-gray-300 p-7 text-center dark:border-white/15"><Paperclip className="mx-auto h-5 w-5 text-gray-300" /><p className="mt-2 text-sm font-semibold">Attach supporting files</p><p className="mt-1 text-xs text-gray-400">Files will use private signed storage uploads.</p></div></EditorCard></main>
    <aside className="h-fit space-y-5 xl:sticky xl:top-20"><EditorCard title="Metadata"><Select label="Question type" value={type} onChange={(value) => setType(value as QuestionType)} options={QUESTION_TYPES.map(([value,label]) => ({ value, label }))} /><Select label="Difficulty" options={['Easy','Medium','Hard']} /><div className="grid grid-cols-2 gap-3"><Field label="Marks"><input type="number" defaultValue="1" min="0" step="0.5" className="editor-input" /></Field><Field label="Negative"><input type="number" defaultValue="0" min="0" step="0.25" className="editor-input" /></Field></div><Field label="Estimated time"><input type="number" placeholder="Seconds" className="editor-input" /></Field><Select label="Language" options={['English','Hindi']} /><Select label="Bloom level" options={['Remember','Understand','Apply','Analyze','Evaluate','Create']} /></EditorCard><EditorCard title="Academic tagging"><Select label="Academic year" options={['Select year']} /><Select label="Grade" options={['Select grade']} /><Select label="Subject" options={['Select subject']} /><Select label="Chapter" options={['Select chapter']} /><Select label="Topic" options={['Select topic']} /><Field label="Skills, outcomes & tags"><input placeholder="Add tags…" className="editor-input" /></Field></EditorCard></aside></div>}
  </div>
}

function EditorCard({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-3xl border border-gray-200/80 bg-white p-5 shadow-sm dark:border-white/10 dark:bg-gray-900 sm:p-6"><h2 className="mb-5 font-semibold text-gray-950 dark:text-white">{title}</h2><div className="space-y-5">{children}</div></section> }
function Field({ label, hint, children }: { label: string; hint?: string; children: React.ReactNode }) { return <label className="block"><span className="text-xs font-semibold text-gray-700 dark:text-gray-300">{label}</span>{hint && <span className="ml-2 text-[11px] text-gray-400">{hint}</span>}<div className="mt-2">{children}</div></label> }
function Tool({ icon: Icon, label }: { icon: typeof ImagePlus; label: string }) { return <button className="inline-flex items-center gap-1.5 rounded-lg px-2.5 py-1.5 text-xs font-medium text-gray-500 hover:bg-gray-100 dark:hover:bg-white/5"><Icon className="h-3.5 w-3.5" />{label}</button> }
function Select({ label, options, value, onChange }: { label: string; options: readonly (string | { value: string; label: string })[]; value?: string; onChange?: (value: string) => void }) { return <Field label={label}><div className="relative"><select value={value} onChange={(event) => onChange?.(event.target.value)} className="editor-input appearance-none pr-8">{options.map((option) => { const item = typeof option === 'string' ? { value: option.toLowerCase(), label: option } : option; return <option key={item.value} value={item.value}>{item.label}</option> })}</select><ChevronDown className="pointer-events-none absolute right-3 top-3 h-3.5 w-3.5 text-gray-400" /></div></Field> }
function QuestionPreview({ title, body, type }: { title: string; body: string; type: QuestionType }) { return <div className="mx-auto max-w-3xl rounded-3xl border border-gray-200 bg-white p-8 shadow-sm dark:border-white/10 dark:bg-gray-900"><span className="text-xs font-bold uppercase tracking-wide text-blue-600">Student preview · {type.replaceAll('_',' ')}</span><h2 className="mt-5 text-xl font-semibold">{title || 'Untitled question'}</h2><p className="mt-4 whitespace-pre-wrap text-sm leading-7 text-gray-600 dark:text-gray-300">{body || 'Question content will appear here.'}</p></div> }
